export type ExerciseLevel = 'iniciante' | 'medio' | 'profissional' | 'expert';

export type VocalExercise = {
  id: number;
  blockId?: "bloco-1" | "bloco-2";
  frontId?: string;
  frontName?: string;
  frontCode?: string;
  frontGroup?: string;
  order?: number;
  partBMode?: "texto" | "sequencia" | "improvisacao" | "movimento";
  criteria?: [string, string, string, string, string];
  dayId: string;
  dayName: string;
  dayFocus: string;
  levelId: ExerciseLevel;
  levelName: string;
  title: string;
  instructions: string;
  durationSeconds: number | null;
  repetitions: number | null;
  partA: string;
  partB: string;
};

export const weeklyRoutine: VocalExercise[] = [
  {
    "id": 1,
    "dayId": "segunda",
    "dayName": "Segunda-feira",
    "dayFocus": "Frente de Fluxo Aéreo e Estabilidade Respiratória",
    "levelId": "iniciante",
    "levelName": "Iniciante",
    "title": "Sopro Fricativo com Espaguete (SSSSS)",
    "instructions": "Sucção leve com o canudo (espaguete) seguida de sopro contínuo estilo sibilo de cobra (sssss) por 8 segundos. 5 repetições.",
    "durationSeconds": 8,
    "repetitions": 5,
    "partA": "SSSSSSSSSSSSSSSSSSSSSS",
    "partB": "O vento sopra suave... sinto o ar fluir... tudo calmo."
  },
  {
    "id": 2,
    "dayId": "segunda",
    "dayName": "Segunda-feira",
    "dayFocus": "Frente de Fluxo Aéreo e Estabilidade Respiratória",
    "levelId": "iniciante",
    "levelName": "Iniciante",
    "title": "Vibração Labial Contínua Curta (VVVV)",
    "instructions": "Emitir vvvv de forma contínua e suave na região dos lábios por 5 segundos. 5 repetições.",
    "durationSeconds": 5,
    "repetitions": 5,
    "partA": "VVVVVVVVVVVVVVVV",
    "partB": "A brisa leve... toca o rosto... ar constante."
  },
  {
    "id": 3,
    "dayId": "segunda",
    "dayName": "Segunda-feira",
    "dayFocus": "Frente de Fluxo Aéreo e Estabilidade Respiratória",
    "levelId": "iniciante",
    "levelName": "Iniciante",
    "title": "Sustentação de Vogal com Fluxo Livre",
    "instructions": "Inspirar profundamente e emitir a vogal A com volume moderado e foco exclusivo na saída de ar sem bloqueio.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "AAAAAAAAAAAAAAAA",
    "partB": "Ahhh... o ar sai livre... sem esforço."
  },
  {
    "id": 4,
    "dayId": "segunda",
    "dayName": "Segunda-feira",
    "dayFocus": "Frente de Fluxo Aéreo e Estabilidade Respiratória",
    "levelId": "medio",
    "levelName": "Médio",
    "title": "Controle de Fôlego com Fricção Alternada (SSSS - FFFF)",
    "instructions": "Alternar 4 segundos de SSSS com 4 segundos de FFFF (fricção nos dentes superiores e lábio inferior). 3 ciclos.",
    "durationSeconds": 4,
    "repetitions": 3,
    "partA": "SSSSSSSSSSSSSS, FFFFFFFFFFFFFF",
    "partB": "O fluxo contínuo do ar sustenta a palavra sem que a garganta precise fazer qualquer força mecânica."
  },
  {
    "id": 5,
    "dayId": "segunda",
    "dayName": "Segunda-feira",
    "dayFocus": "Frente de Fluxo Aéreo e Estabilidade Respiratória",
    "levelId": "medio",
    "levelName": "Médio",
    "title": "Vibração Labial com Contorno Descendente",
    "instructions": "Emitir VVVV iniciando no médio e descendo para o grave em 6 segundos. 4 repetições.",
    "durationSeconds": 6,
    "repetitions": 4,
    "partA": "VVVVVVVVVVVVVVV",
    "partB": "A água desce o rio... calma e constante... rumo ao fundo."
  },
  {
    "id": 6,
    "dayId": "segunda",
    "dayName": "Segunda-feira",
    "dayFocus": "Frente de Fluxo Aéreo e Estabilidade Respiratória",
    "levelId": "medio",
    "levelName": "Médio",
    "title": "Leitura de Frases com Pausas Respiratórias Estritas",
    "instructions": "Ler frases curtas respirando estritamente a cada ponto final, mantendo o abdômen firme.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "FFFFFFFFFFFFFFF",
    "partB": "O dia amanhece tranquilo. O ar preenche o peito. A voz emerge sem pressa."
  },
  {
    "id": 7,
    "dayId": "segunda",
    "dayName": "Segunda-feira",
    "dayFocus": "Frente de Fluxo Aéreo e Estabilidade Respiratória",
    "levelId": "profissional",
    "levelName": "Profissional",
    "title": "Sustentação de Fluxo sob Pressão Controlada (VVVV + SSSS)",
    "instructions": "Executar 10 segundos de VVVV seguidos imediatamente de 10 segundos de SSSS em uma única inspiração diafragmática.",
    "durationSeconds": 10,
    "repetitions": null,
    "partA": "VVVVVVVVVVVV,",
    "partB": "O fôlego controlado é a ferramenta invisível do grande orador. Ele permite que frases longas sejam entregues com a mesma densidade do início ao fim."
  },
  {
    "id": 8,
    "dayId": "segunda",
    "dayName": "Segunda-feira",
    "dayFocus": "Frente de Fluxo Aéreo e Estabilidade Respiratória",
    "levelId": "profissional",
    "levelName": "Profissional",
    "title": "Leitura de Parágrafo com Coluna de Ar Contínua",
    "instructions": "Ler um parágrafo inteiro de estilo narrativo utilizando uma única inspiração, focando na economia e no direcionamento do fluxo aéreo.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "SSSSSSSSSSSSSSSSSSS",
    "partB": "O fluxo constante do ar é o alicerce sobre o qual construímos cada palavra. Quando o suporte abdominal e a vibração labial se alinham perfeitamente, a voz ganha uma estabilidade inabalável, capaz de atravessar longas sentenças sem perder a densidade no registro grave."
  },
  {
    "id": 9,
    "dayId": "segunda",
    "dayName": "Segunda-feira",
    "dayFocus": "Frente de Fluxo Aéreo e Estabilidade Respiratória",
    "levelId": "profissional",
    "levelName": "Profissional",
    "title": "Glissando de Fluxo com Conexão Abdominal",
    "instructions": "Emitir um som fricativo ZZZZ fazendo uma curva melódica (subindo e descendo) guiada exclusivamente pelo apoio abdominal.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "ZZZZZZZZZZZZZZZ",
    "partB": "A musculatura abdominal atua como o pistão que regula a pressão do ar, garantindo que o som grave permaneça macio e encorpado."
  },
  {
    "id": 10,
    "dayId": "segunda",
    "dayName": "Segunda-feira",
    "dayFocus": "Frente de Fluxo Aéreo e Estabilidade Respiratória",
    "levelId": "expert",
    "levelName": "Expert",
    "title": "Monólogo de Fôlego Profundo com Fricção e Fala",
    "instructions": "Executar 15 segundos de vibração labial VVVV em crescendo e decrescendo, seguidos imediatamente pela leitura de um monólogo filosófico.",
    "durationSeconds": 15,
    "repetitions": null,
    "partA": "VVVVVVVVVVVVVVVVV",
    "partB": "Na disciplina rigorosa do fluxo aéreo reside o verdadeiro poder da emissão vocal. O ar não é apenas o combustível biológico, mas o veículo dinâmico que transporta a intenção sem atrito mecânico, revelando a maestria absoluta do controle respiratório em sua forma mais pura, ininterrupta e soberana."
  },
  {
    "id": 11,
    "dayId": "segunda",
    "dayName": "Segunda-feira",
    "dayFocus": "Frente de Fluxo Aéreo e Estabilidade Respiratória",
    "levelId": "expert",
    "levelName": "Expert",
    "title": "Leitura de Texto Técnico com Controle de Pressão Subglótica",
    "instructions": "Ler um texto técnico denso mantendo a sensação de sopro interno (como se estivesse sussurrando por dentro da voz fonada).",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "VVVVVVVVVVVVVVVVVV",
    "partB": "A regulação hidrodinâmica do trato vocal exige que a pressão subglótica permaneça perfeitamente equilibrada com a resistência glótica. Qualquer desvio nesse gradiente de pressão resulta em fadiga precoce ou perda de ressonância no registro grave."
  },
  {
    "id": 12,
    "dayId": "segunda",
    "dayName": "Segunda-feira",
    "dayFocus": "Frente de Fluxo Aéreo e Estabilidade Respiratória",
    "levelId": "expert",
    "levelName": "Expert",
    "title": "Improvisação de Fluxo Contínuo sob Pressão Emocional",
    "instructions": "Improvisar uma fala dramática de 1 minuto mantendo a consciência do fluxo de ar saindo como um fio contínuo e gelado.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "VVVVVVVVVVVVVVVVV",
    "partB": "Mesmo nas tempestades mais violentas, o eixo central permanece intacto. O ar flui, a voz resiste, e a estrutura não se rompe, porque a base foi construída sobre a rocha sólida da respiração consciente."
  },
  {
    "id": 13,
    "dayId": "terca",
    "dayName": "Terça-feira",
    "dayFocus": "Frente de Ressonância Nasal e Soltura Lingual",
    "levelId": "iniciante",
    "levelName": "Iniciante",
    "title": "Nasal Básico (MMMM)",
    "instructions": "Boca fechada, dentes encostados sem força, emitindo mmmm com foco de vibração nos lábios e nariz por 8 segundos. 5 repetições.",
    "durationSeconds": 8,
    "repetitions": 5,
    "partA": "MMMMMMMMMMMMMM",
    "partB": "Mmm... que bom... sinto o rosto vibrar."
  },
  {
    "id": 14,
    "dayId": "terca",
    "dayName": "Terça-feira",
    "dayFocus": "Frente de Ressonância Nasal e Soltura Lingual",
    "levelId": "iniciante",
    "levelName": "Iniciante",
    "title": "Trinado Lingual Curto (RRRRR)",
    "instructions": "Emitir rrrrr com a ponta da língua solta e fluxo de ar constante por 4 segundos. 5 repetições.",
    "durationSeconds": 4,
    "repetitions": 5,
    "partA": "MMMMMMMMMMMMMM",
    "partB": "Rrrrr... língua solta... sem tensão."
  },
  {
    "id": 15,
    "dayId": "terca",
    "dayName": "Terça-feira",
    "dayFocus": "Frente de Ressonância Nasal e Soltura Lingual",
    "levelId": "iniciante",
    "levelName": "Iniciante",
    "title": "Alternância M-R (Zumbido e Trinado)",
    "instructions": "Alternar 3 segundos de MMMM com 3 segundos de RRRRR em tom confortável.",
    "durationSeconds": 3,
    "repetitions": null,
    "partA": "MMMMMMMM, RRRRRRRRR",
    "partB": "Mmm... rrrrr... soltando a face e a língua."
  },
  {
    "id": 16,
    "dayId": "terca",
    "dayName": "Terça-feira",
    "dayFocus": "Frente de Ressonância Nasal e Soltura Lingual",
    "levelId": "medio",
    "levelName": "Médio",
    "title": "Vibração Nasal com Vogais Curtas (M-A-M-O-M-U)",
    "instructions": "Iniciar com M longo e abrir para vogais mantendo a sensação de zumbido no nariz.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "Frases/Textos; MMMMMAAAAA, MMMMMMOOOOO, MMMMMMUUUUU...",
    "partB": "Ma... mo... mu... a ressonância toca a máscara facial."
  },
  {
    "id": 17,
    "dayId": "terca",
    "dayName": "Terça-feira",
    "dayFocus": "Frente de Ressonância Nasal e Soltura Lingual",
    "levelId": "medio",
    "levelName": "Médio",
    "title": "Trinado Lingual com Pequena Curva de Tom",
    "instructions": "Fazer um rrrrr subindo e descendo levemente o tom, mantendo a mandíbula relaxada.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "Frases/Textos; RRRRRRRRRRR....",
    "partB": "O som vibra nos dentes e a língua flutua livre sobre o assoalho da boca."
  },
  {
    "id": 18,
    "dayId": "terca",
    "dayName": "Terça-feira",
    "dayFocus": "Frente de Ressonância Nasal e Soltura Lingual",
    "levelId": "medio",
    "levelName": "Médio",
    "title": "Leitura com Foco em Consoantes Nasais (M, N, NH)",
    "instructions": "Ler frases focando na sensação de cócegas no nariz proporcionada pelas consoantes nasais.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "Frases/Textos; MMMMMMMMMMMM, NNNNNNNNN",
    "partB": "Muitos meninos caminham no campo, ouvindo o murmúnio manso da manhã."
  },
  {
    "id": 19,
    "dayId": "terca",
    "dayName": "Terça-feira",
    "dayFocus": "Frente de Ressonância Nasal e Soltura Lingual",
    "levelId": "profissional",
    "levelName": "Profissional",
    "title": "Zumbido Nasal em Crescendo com Projeção Óssea",
    "instructions": "Emitir MMMM iniciando suave e aumentando o volume até sentir os ossos da maçã do rosto e testa vibrarem intensamente.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "Frases/Textos; MMMMMMMMMM....",
    "partB": "A ressonância óssea é o amplificador natural que a natureza concedeu à voz humana, permitindo que o som grave ganhe eco sem o menor esforço laríngeo."
  },
  {
    "id": 20,
    "dayId": "terca",
    "dayName": "Terça-feira",
    "dayFocus": "Frente de Ressonância Nasal e Soltura Lingual",
    "levelId": "profissional",
    "levelName": "Profissional",
    "title": "Trinado Lingual Aplicado a Textos Articulados",
    "instructions": "Executar um trinado lingual contínuo de 8 segundos e imediatamente ler um parágrafo com alta densidade de consoantes líquidas (L, R).",
    "durationSeconds": 8,
    "repetitions": null,
    "partA": "Frases/Textos; LLLLLLLLLLLL....",
    "partB": "No topo da montanha, o vento sussurra nas rochas ancestrais. A vibração nasal preenche o espaço craniano, enquanto a língua dança livre, sem amarras, transformando cada consoante vibrante em pura energia sonora."
  },
  {
    "id": 21,
    "dayId": "terca",
    "dayName": "Terça-feira",
    "dayFocus": "Frente de Ressonância Nasal e Soltura Lingual",
    "levelId": "profissional",
    "levelName": "Profissional",
    "title": "Sequência Mista de Soltura (Nasal + Lingual + Mandibular)",
    "instructions": "Ciclo de 5s de MMM, 5s de RRR e 5s de L-L-L (lateralização da língua) repetido 3 vezes.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "Frases/Textos; MMMMM..., RRRRR..., LLLLL....",
    "partB": "Libertar a raiz da língua é abrir as portas para que o registro grave desça com toda a sua plenitude e riqueza timbrística."
  },
  {
    "id": 22,
    "dayId": "terca",
    "dayName": "Terça-feira",
    "dayFocus": "Frente de Ressonância Nasal e Soltura Lingual",
    "levelId": "expert",
    "levelName": "Expert",
    "title": "Monólogo de Ressonância Craniana Extrema",
    "instructions": "Executar um zumbido nasal intenso por 10 segundos e em seguida declamar um monólogo mantendo o eco na máscara facial mesclado ao grave profundo.",
    "durationSeconds": 10,
    "repetitions": null,
    "partA": "Frases/Textos; NNNNNNNN...",
    "partB": "A ressonância na máscara e a soltura implacável da língua formam a aliança secreta da projeção sem esforço. Quando o som encontra eco nos ossos da face e a língua vibra com total liberdade, a palavra falada adquire uma clarividência cortante, capaz de atravessar qualquer distância enquanto a laringe permanece em repouso absoluto."
  },
  {
    "id": 23,
    "dayId": "terca",
    "dayName": "Terça-feira",
    "dayFocus": "Frente de Ressonância Nasal e Soltura Lingual",
    "levelId": "expert",
    "levelName": "Expert",
    "title": "Trava-línguas de Alta Velocidade com Base Nasal",
    "instructions": "Emitir um zumbido MMM de preparação e ler rapidamente um trava-línguas complexo focado em R e L sem perder o foco na máscara.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "Frases/Textos; MMMMMMM...",
    "partB": "O rato roeu a roupa do rei de Roma, enquanto a rainha rindo ressoava resmungos rudes na redoma rústica, revelando a rigidez da raiz lingual totalmente dissolvida pela ressonância."
  },
  {
    "id": 24,
    "dayId": "terca",
    "dayName": "Terça-feira",
    "dayFocus": "Frente de Ressonância Nasal e Soltura Lingual",
    "levelId": "expert",
    "levelName": "Expert",
    "title": "Improvisação de Timbre Metálico e Nasal com Grave Ancorado",
    "instructions": "Improvisar um discurso solene misturando o brilho da máscara anterior com a profundidade do peito.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "Frases/Textos; NNNNNN....MMMMM....",
    "partB": "A verdadeira autoridade vocal não reside na força bruta da garganta, mas na arquitetura perfeita da ressonância. A máscara anterior fornece o brilho cortante, o peito fornece o peso telúrico, e a língua solta garante a inteligibilidade suprema da mensagem."
  },
  {
    "id": 25,
    "dayId": "quarta",
    "dayName": "Quarta-feira",
    "dayFocus": "Frente de Ressonância Torácica e Tons Graves",
    "levelId": "iniciante",
    "levelName": "Iniciante",
    "title": "Emissão de Vogal Escura com Mão no Peito (UUUUU)",
    "instructions": "Colocar a mão sobre o osso esterno, inspirar profundamente e emitir a vogal U em tom grave e confortável por 6 segundos, sentindo a vibração mecânica na mão. 5 repetições.",
    "durationSeconds": 6,
    "repetitions": 5,
    "partA": "Frases/Textos; UUUUUU.......",
    "partB": "Uuuuu... fundo... escuro... sinto o peito vibrar."
  },
  {
    "id": 26,
    "dayId": "quarta",
    "dayName": "Quarta-feira",
    "dayFocus": "Frente de Ressonância Torácica e Tons Graves",
    "levelId": "iniciante",
    "levelName": "Iniciante",
    "title": "Fricção Contínua com Descida de Tom (JJJJ)",
    "instructions": "Emitir o som fricativo JJJJ (como um sussurro aspirado ou chiado grave) descendo do médio para o grave. 5 repetições.",
    "durationSeconds": null,
    "repetitions": 5,
    "partA": "Frases/Textos; JJJJJJJJJJ....",
    "partB": "Jjjj... desce o tom... rumo ao grave."
  },
  {
    "id": 27,
    "dayId": "quarta",
    "dayName": "Quarta-feira",
    "dayFocus": "Frente de Ressonância Torácica e Tons Graves",
    "levelId": "iniciante",
    "levelName": "Iniciante",
    "title": "Alternância O-U em Tom Baixo",
    "instructions": "Alternar lentamente entre Oooo e Uuuu em tom grave, mantendo a boca arredondada. 4 repetições.",
    "durationSeconds": null,
    "repetitions": 4,
    "partA": "Frases/Textos; OOOOOOO...UUUUUUU...",
    "partB": "Ooo... uuu... redondos e profundos."
  },
  {
    "id": 28,
    "dayId": "quarta",
    "dayName": "Quarta-feira",
    "dayFocus": "Frente de Ressonância Torácica e Tons Graves",
    "levelId": "medio",
    "levelName": "Médio",
    "title": "Sustentação de Vogal Escura com Apoio Diafragmático",
    "instructions": "Emitir UUUUU contínuo por 10 segundos, mantendo o abdômen contraído para sustentar o grave sem esmagar a laringe. 3 repetições.",
    "durationSeconds": 10,
    "repetitions": 3,
    "partA": "Frases/Textos; UUUUUUUUUUUUU...",
    "partB": "O som profundo do tambor ecoa no peito, revelando o timbre mais íntimo e acolhedor da nossa voz."
  },
  {
    "id": 29,
    "dayId": "quarta",
    "dayName": "Quarta-feira",
    "dayFocus": "Frente de Ressonância Torácica e Tons Graves",
    "levelId": "medio",
    "levelName": "Médio",
    "title": "Glissando Descendente com Vogal 'O'",
    "instructions": "Iniciar o Oooo no topo da extensão e deslizar em tobogã até o grave mais profundo, ancorando no esterno. 4 repetições.",
    "durationSeconds": null,
    "repetitions": 4,
    "partA": "Frases/Textos; OOOOOOO...",
    "partB": "A noite cai lentamente, puxando o som para as camadas mais baixas da terra."
  },
  {
    "id": 30,
    "dayId": "quarta",
    "dayName": "Quarta-feira",
    "dayFocus": "Frente de Ressonância Torácica e Tons Graves",
    "levelId": "medio",
    "levelName": "Médio",
    "title": "Leitura de Frases Curtas com Foco em Vogais Posteriores",
    "instructions": "Ler frases focando no abaixamento da base da língua para escurecer o timbre.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "Frases/Textos; OOOOOOO....",
    "partB": "O urso pardo dorme no fundo da gruta escura, embalado pelo murmúrio do mundo."
  },
  {
    "id": 31,
    "dayId": "quarta",
    "dayName": "Quarta-feira",
    "dayFocus": "Frente de Ressonância Torácica e Tons Graves",
    "levelId": "profissional",
    "levelName": "Profissional",
    "title": "Emissão Prolongada em Registro Grave com Dinâmica (UUUU - OOOO)",
    "instructions": "Executar 15 segundos de transição fluida entre UUU e OOO em tom profundamente grave, alternando volume suave e encorpado.",
    "durationSeconds": 15,
    "repetitions": null,
    "partA": "Frases/Textos; UUUUUUU...",
    "partB": "Nas profundezas do oceano, a pressão molda a imensidão. Da mesma forma, a ressonância torácica molda o registro grave, conferindo à voz uma densidade magnética e uma autoridade incontestável."
  },
  {
    "id": 32,
    "dayId": "quarta",
    "dayName": "Quarta-feira",
    "dayFocus": "Frente de Ressonância Torácica e Tons Graves",
    "levelId": "profissional",
    "levelName": "Profissional",
    "title": "Leitura de Texto Dramático com Ancoragem Esternal",
    "instructions": "Ler um parágrafo narrativo mantendo a sensação física de que as palavras estão sendo geradas diretamente no osso do peito.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "Frases/Textos; OOOOOO...",
    "partB": "O peso do mundo não se carrega nos ombros, mas se ancora no peito. Quando a voz encontra seu refúgio na caixa torácica, cada sílaba adquire o peso de um manifesto, ecoando com a solidez de uma catedral antiga."
  },
  {
    "id": 33,
    "dayId": "quarta",
    "dayName": "Quarta-feira",
    "dayFocus": "Frente de Ressonância Torácica e Tons Graves",
    "levelId": "profissional",
    "levelName": "Profissional",
    "title": "Sequência de Ataques Vocales Suaves em Tons Baixos",
    "instructions": "Emitir palavras monossílabas graves (luz, som, mar, chão) com ataque suave (sem golpe de glote) e máxima ressonância torácica.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "Frases/Textos; OOOOOOO..., UUUUUUU...",
    "partB": "Mar, chão, som, voz. Cada palavra é uma âncora que prende o ouvinte à solidez do momento presente."
  },
  {
    "id": 34,
    "dayId": "quarta",
    "dayName": "Quarta-feira",
    "dayFocus": "Frente de Ressonância Torácica e Tons Graves",
    "levelId": "expert",
    "levelName": "Expert",
    "title": "Monólogo de Autoridade e Ressonância Telúrica",
    "instructions": "Iniciar com um suspiro grave ancorado no peito e declamar um monólogo de alta densidade existencial mantendo a laringe totalmente abaixada.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "Frases/Textos; AHAHAHAHAHAHAH..",
    "partB": "O domínio do registro grave através da ressonância torácica não é apenas uma mecânica acústica, mas um estado de presença absoluta. Quando o som 'U' e 'O' reverbera no osso esterno, ele desperta a ancestralidade da palavra, transformando cada enunciado em um decreto de inabalável convicção, serenidade e poder telúrico."
  },
  {
    "id": 35,
    "dayId": "quarta",
    "dayName": "Quarta-feira",
    "dayFocus": "Frente de Ressonância Torácica e Tons Graves",
    "levelId": "expert",
    "levelName": "Expert",
    "title": "Leitura Interpretativa de Poesia Épica em Tessitura Baixa",
    "instructions": "Ler estrofes épicas mantendo o centro de gravidade da voz no limite inferior da tessitura falada, sem perder a inteligibilidade.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "Frases/Textos; AHAHAHAHAH...",
    "partB": "Das entranhas da terra surge o rugido dos antigos tempos. Onde o ferro encontra o fogo e a rocha encontra o mar. O destino é um martelo que molda o mundo na penumbra, e a voz que narra essa epopeia deve ser tão profunda quanto o abismo que descreve."
  },
  {
    "id": 36,
    "dayId": "quarta",
    "dayName": "Quarta-feira",
    "dayFocus": "Frente de Ressonância Torácica e Tons Graves",
    "levelId": "expert",
    "levelName": "Expert",
    "title": "Improvisação de Comando Soberano com Timbre Escuro",
    "instructions": "Improvisar um discurso de liderança mantendo o foco absoluto na caixa torácica e na lentidão deliberada do fraseado.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "Frases/Textos; AHAHAHAHAHAH....",
    "partB": "Não há tempestade capaz de abalar aquele que encontrou o seu centro. A verdadeira força não grita; ela ressoa com a calma imponente de uma montanha que observa o tempo passar, sustentada pela gravidade imutável dos grandes abismos."
  },
  {
    "id": 37,
    "dayId": "quinta",
    "dayName": "Quinta-feira",
    "dayFocus": "Frente de Projeção e Máscara Anterior",
    "levelId": "iniciante",
    "levelName": "Iniciante",
    "title": "Zumbido Sonoro Frontal (ZZZZZ)",
    "instructions": "Dentes encostados levemente, emitindo zzzzz com foco de cócegas nos lábios e dentes frontais por 6 segundos. 5 repetições.",
    "durationSeconds": 6,
    "repetitions": 5,
    "partA": "Frases/Textos; ZZZZZZZZ...",
    "partB": "Zzzzz... vibrando nos dentes... projeção limpa."
  },
  {
    "id": 38,
    "dayId": "quinta",
    "dayName": "Quinta-feira",
    "dayFocus": "Frente de Projeção e Máscara Anterior",
    "levelId": "iniciante",
    "levelName": "Iniciante",
    "title": "Vibração Labial com Direcionamento Anterior (VVVV)",
    "instructions": "Emitir vvvv direcionando o sopro diretamente para os lábios superiores, imaginando o som saindo pelo nariz e dentes. 5 repetições.",
    "durationSeconds": null,
    "repetitions": 5,
    "partA": "Frases/Textos; VVVVVVVVVV...",
    "partB": "Vvvv... o som vai para frente... sem esforço."
  },
  {
    "id": 39,
    "dayId": "quinta",
    "dayName": "Quinta-feira",
    "dayFocus": "Frente de Projeção e Máscara Anterior",
    "levelId": "iniciante",
    "levelName": "Iniciante",
    "title": "Emissão de Consoantes Explosivas Curtas (P-T-K)",
    "instructions": "Pronunciar pra-tra-kra de forma enérgica e frontal, mantendo a mandíbula solta. 4 repetições.",
    "durationSeconds": null,
    "repetitions": 4,
    "partA": "Frases/Textos; PA, TA, KA, - PA,TA,KA, - PA, TA, KA",
    "partB": "KA,PA,TA, - KA,PA,TA, - , KA,PA,TA."
  },
  {
    "id": 40,
    "dayId": "quinta",
    "dayName": "Quinta-feira",
    "dayFocus": "Frente de Projeção e Máscara Anterior",
    "levelId": "medio",
    "levelName": "Médio",
    "title": "Alternância V-Z (Vibração e Zumbido)",
    "instructions": "Alternar 4 segundos de VVVV com 4 segundos de ZZZZZ, sentindo o foco móvel na máscara anterior. 3 ciclos.",
    "durationSeconds": 4,
    "repetitions": 3,
    "partA": "VVVVVVVVVVVVV, ZZZZZZZZZZZZ",
    "partB": "A luz ziguezagueia no horizonte, projetando clareza e brilho em cada vogal emitida."
  },
  {
    "id": 41,
    "dayId": "quinta",
    "dayName": "Quinta-feira",
    "dayFocus": "Frente de Projeção e Máscara Anterior",
    "levelId": "medio",
    "levelName": "Médio",
    "title": "Leitura com Articulação Labial Exagerada",
    "instructions": "Ler frases curtas abrindo bem os lábios e projetando o som para fora dos dentes.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "VVVVVVVVVVVVVV",
    "partB": "O vento fresco bate na janela, trazendo nitidez e vivacidade para cada palavra."
  },
  {
    "id": 42,
    "dayId": "quinta",
    "dayName": "Quinta-feira",
    "dayFocus": "Frente de Projeção e Máscara Anterior",
    "levelId": "medio",
    "levelName": "Médio",
    "title": "Glissando Ascendente-Descendente na Máscara",
    "instructions": "Emitir um M-M-M que sobe levemente para a máscara e desce para o peito, mantendo o brilho frontal. 4 repetições.",
    "durationSeconds": null,
    "repetitions": 4,
    "partA": "M—M-M-M-M-M-M-M",
    "partB": "O som viaja da face ao peito, unindo brilho e profundidade."
  },
  {
    "id": 43,
    "dayId": "quinta",
    "dayName": "Quinta-feira",
    "dayFocus": "Frente de Projeção e Máscara Anterior",
    "levelId": "profissional",
    "levelName": "Profissional",
    "title": "Zumbido Frontal em Crescendo Dinâmico (ZZZZZ)",
    "instructions": "Executar 12 segundos de ZZZZZ aumentando o foco nos dentes frontais até criar uma sensação de feixe laser sonoro.",
    "durationSeconds": 12,
    "repetitions": null,
    "partA": "ZZZZZZZZZZZZZZZZZZZZZZ",
    "partB": "A projeção eficaz não depende de gritar, mas de focalizar o som na máscara anterior. Com os lábios ativos e dentes livres, a voz ganha um brilho metálico que corta o ar sem causar atrito na laringe."
  },
  {
    "id": 44,
    "dayId": "quinta",
    "dayName": "Quinta-feira",
    "dayFocus": "Frente de Projeção e Máscara Anterior",
    "levelId": "profissional",
    "levelName": "Profissional",
    "title": "Leitura de Texto Informativo com Foco Cirúrgico",
    "instructions": "Ler um texto jornalístico/técnico com articulação frontal acentuada, garantindo que o ouvinte capte até as consoantes mais sutis.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "VVVVVVVVVVVVVV",
    "partB": "A precisão na transmissão da mensagem exige que cada foneme seja moldado na parte anterior da boca. Quando o foco da ressonância se instala nos dentes e lábios, a inteligibilidade atinge o patamar máximo de eficiência acústica."
  },
  {
    "id": 45,
    "dayId": "quinta",
    "dayName": "Quinta-feira",
    "dayFocus": "Frente de Projeção e Máscara Anterior",
    "levelId": "profissional",
    "levelName": "Profissional",
    "title": "Sequência Rápida de Consoantes Fricativas e Oclusivas",
    "instructions": "Articular rapidamente sequências como f-v-s-z-p-t-k com projeção frontal limpa.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "FA, VA, SA, ZA, PA, TA, KA – FA, VA, AS, ZA, PA, TA, KA.",
    "partB": "Foco, força, clareza, projeção. A máscara anterior é o alto-falante natural do corpo humano."
  },
  {
    "id": 46,
    "dayId": "quinta",
    "dayName": "Quinta-feira",
    "dayFocus": "Frente de Projeção e Máscara Anterior",
    "levelId": "expert",
    "levelName": "Expert",
    "title": "Monólogo de Projeção e Alcance Espacial",
    "instructions": "Emitir um zumbido ZZZ de alta intensidade e declamar um discurso persuasivo imaginando projetar a voz para o fundo de um teatro lotado, mantendo a laringe baixa.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "ZZZZZZZZZZZZZZZZ",
    "partB": "A excelência da comunicação exige que a voz alcance o ouvinte mais distante com a mesma intimidade com que sussurra ao ouvido mais próximo. A ativação precisa da máscara anterior através do zumbido sonoro 'ZZZZZ' garante essa omnipresença acústica, unindo brilho cristalino, projeção cirúrgica e autoridade inabalável."
  },
  {
    "id": 47,
    "dayId": "quinta",
    "dayName": "Quinta-feira",
    "dayFocus": "Frente de Projeção e Máscara Anterior",
    "levelId": "expert",
    "levelName": "Expert",
    "title": "Recital de Texto Poético com Brilho Metálico e Grave Profundo",
    "instructions": "Combinar a projeção frontal das vogais abertas com a ancoragem torácica das vogais fechadas em um poema de alta exigência.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "PÁ, MAR, CASA- PÉ, CAFÉ, PÓ, AVÓ, SOL\nVÊ, VOCÊ, MESA,AVÔ, POVO, OVO, VIDA, CRU, UVA",
    "partB": "No cristal da manhã, o reflexo do sol brilha implacável. Assim também deve ser a nossa expressão: afiada como uma lâmina na frente, profunda como o oceano por dentro. Projeção e raiz caminhando juntas na conquista absoluta da atenção alheia."
  },
  {
    "id": 48,
    "dayId": "quinta",
    "dayName": "Quinta-feira",
    "dayFocus": "Frente de Projeção e Máscara Anterior",
    "levelId": "expert",
    "levelName": "Expert",
    "title": "Improvisação de Alerta ou Comando com Foco Frontal Absoluto",
    "instructions": "Improvisar uma fala urgente de 45 segundos mantendo a sensação de que o som está sendo disparado diretamente para fora dos dentes superiores.",
    "durationSeconds": 45,
    "repetitions": null,
    "partA": "Atenção ao momento presente. A clareza da visão antecede a força da ação. Quando a voz é projetada com precisão milimétrica na máscara anterior, ela deixa de ser um mero som e passa a ser uma força de impacto que reorganiza o ambiente ao seu redor.",
    "partB": "( IMPROVISO)"
  },
  {
    "id": 49,
    "dayId": "sexta",
    "dayName": "Sexta-feira",
    "dayFocus": "Frente de Integração de Fluxo e Articulação Avançada",
    "levelId": "iniciante",
    "levelName": "Iniciante",
    "title": "Alternância Lenta M-S (Nasal e Sopro)",
    "instructions": "Emitir MMMM por 4 segundos e transitar imediatamente para SSSSS por 4 segundos. 4 repetições.",
    "durationSeconds": 4,
    "repetitions": 4,
    "partA": "MMMMMMMM, SSSSSSSSSSSSS",
    "partB": "Mmm... sopro... ar e som unidos."
  },
  {
    "id": 50,
    "dayId": "sexta",
    "dayName": "Sexta-feira",
    "dayFocus": "Frente de Integração de Fluxo e Articulação Avançada",
    "levelId": "iniciante",
    "levelName": "Iniciante",
    "title": "Trinado Labial Curto com Consoante Oclusiva",
    "instructions": "Fazer um VVV de 3 segundos e articular uma palavra curta (porta, tempo). 5 repetições.",
    "durationSeconds": 3,
    "repetitions": 5,
    "partA": "VVVVVVVVVVVVV...",
    "partB": "PORTA, TEMPO, PORTA, TEMPO, PORTA, TEMPO."
  },
  {
    "id": 51,
    "dayId": "sexta",
    "dayName": "Sexta-feira",
    "dayFocus": "Frente de Integração de Fluxo e Articulação Avançada",
    "levelId": "iniciante",
    "levelName": "Iniciante",
    "title": "Sustentação de Vogal com Consoante Intervocálica",
    "instructions": "Emitir Aaaa-rrrrr-aaaa em tom confortável e contínuo. 4 repetições.",
    "durationSeconds": null,
    "repetitions": 4,
    "partA": "AAAAAAAAAA, RRRRRRRRRRRRRR, AAAAAAAAA",
    "partB": "AAAAAAAAAA, RRRRRRRRRRRRRR, AAAAAAAAA\nAAAAAAAAAA, RRRRRRRRRRRRRR, AAAAAAAAA\nAAAAAAAAAA, RRRRRRRRRRRRRR, AAAAAAAAA"
  },
  {
    "id": 52,
    "dayId": "sexta",
    "dayName": "Sexta-feira",
    "dayFocus": "Frente de Integração de Fluxo e Articulação Avançada",
    "levelId": "medio",
    "levelName": "Médio",
    "title": "Alternância Contínua S-R (Sopro e Trinado Lingual)",
    "instructions": "Alternar 4 segundos de SSSS e 4 segundos de RRRRR sem inspirar no meio. 3 ciclos.",
    "durationSeconds": 4,
    "repetitions": 3,
    "partA": "SSSSSSSSSS, RRRRRRRRR,\nSSSSSSSSSS, RRRRRRRRR\nSSSSSSSSSS, RRRRRRRRR",
    "partB": "O vento sopra rindo pelas frestas, unindo o fluxo do ar à leveza da língua."
  },
  {
    "id": 53,
    "dayId": "sexta",
    "dayName": "Sexta-feira",
    "dayFocus": "Frente de Integração de Fluxo e Articulação Avançada",
    "levelId": "medio",
    "levelName": "Médio",
    "title": "Leitura com Conexão Legato entre Palavras",
    "instructions": "Ler frases unindo o final de uma palavra ao início da outra sem quebrar o fluxo do ar.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "Frases/Textos; MMMMMMMMMMM",
    "partB": "A_onda_azul_atravessa_o_espaço_com_fluidez_total."
  },
  {
    "id": 54,
    "dayId": "sexta",
    "dayName": "Sexta-feira",
    "dayFocus": "Frente de Integração de Fluxo e Articulação Avançada",
    "levelId": "medio",
    "levelName": "Médio",
    "title": "Glissando Misto com Vogais e Consoantes",
    "instructions": "Descer o tom emitindo M-R-V em uma única curva contínua. 4 repetições.",
    "durationSeconds": null,
    "repetitions": 4,
    "partA": "Frases/Textos\nMMMMMM-RRRRRR-VVVVVV\nMMMMMM-RRRRRR-VVVVVV\nMMMMMM-RRRRRR-VVVVVV\nMMMMMM-RRRRRR-VVVVVV",
    "partB": "A voz desliza do agudo ao grave, conectando todos os pontos da fonação."
  },
  {
    "id": 55,
    "dayId": "sexta",
    "dayName": "Sexta-feira",
    "dayFocus": "Frente de Integração de Fluxo e Articulação Avançada",
    "levelId": "profissional",
    "levelName": "Profissional",
    "title": "Sequência Longa de Sopro, Zumbido e Trinado (V-M-R)",
    "instructions": "Executar em uma única inspiração: 5s de VVV, 5s de MMM e 5s de RRR. 3 repetições.",
    "durationSeconds": null,
    "repetitions": 3,
    "partA": "Frases/Textos\nVVVVVVVV, MMMMMMM, RRRRRRR\nVVVVVVVV, MMMMMMM, RRRRRRR\nVVVVVVVV, MMMMMMM, RRRRRRR",
    "partB": "A maestria vocal reside na transição imperceptível entre o sopro puro, a ressonância nasal e a vibração articulada. O sistema fonador atinge aqui sua máxima atleticidade."
  },
  {
    "id": 56,
    "dayId": "sexta",
    "dayName": "Sexta-feira",
    "dayFocus": "Frente de Integração de Fluxo e Articulação Avançada",
    "levelId": "profissional",
    "levelName": "Profissional",
    "title": "Leitura de Texto Narrativo com Alternância de Fricativas",
    "instructions": "Ler um parágrafo focado em manter a coluna de ar constante enquanto se articulam sons fricativos complexos (ch, j, s, z).",
    "durationSeconds": null,
    "repetitions": null,
    "partA": ") MMMMMMMMMMMMMM",
    "partB": "A jornada exige precisão cirúrgica. Ao alternar o fluxo aéreo ininterrupto com o trinado lingual e a articulação frontal, o falante desenvolve uma flexibilidade atlética incomparável, unindo potência grave e agilidade extrema."
  },
  {
    "id": 57,
    "dayId": "sexta",
    "dayName": "Sexta-feira",
    "dayFocus": "Frente de Integração de Fluxo e Articulação Avançada",
    "levelId": "profissional",
    "levelName": "Profissional",
    "title": "Exercício de Fôlego Misto com Texto Falado",
    "instructions": "Fazer 10 segundos de vibração labial e, sem respirar, iniciar imediatamente a leitura de uma frase longa em tom grave.",
    "durationSeconds": 10,
    "repetitions": null,
    "partA": "Frases/Textos; BRUUUUUUUUUUUUUU",
    "partB": "O fôlego transformado em som, o som transformado em palavra, a palavra transformada em impacto absoluto sobre quem escuta."
  },
  {
    "id": 58,
    "dayId": "sexta",
    "dayName": "Sexta-feira",
    "dayFocus": "Frente de Integração de Fluxo e Articulação Avançada",
    "levelId": "expert",
    "levelName": "Expert",
    "title": "Monólogo de Integração Total (Fluxo + Ressonância + Articulação)",
    "instructions": "Executar uma preparação respiratória avançada (sopro + zumbido) seguida de um monólogo denso e dinâmico.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "Frases/Textos;UUUUUUUUUUUUUUU",
    "partB": "Integrar o fluxo aéreo, a ressonância profunda e a articulação em alta velocidade é o teste definitivo de coordenação motora vocal. Cada consoante, cada fricativa e cada trinado funcionam como engrenagens perfeitas de um mecanismo soberano que traduz o pensamento em som cristalino, magnético e inabalável."
  },
  {
    "id": 59,
    "dayId": "sexta",
    "dayName": "Sexta-feira",
    "dayFocus": "Frente de Integração de Fluxo e Articulação Avançada",
    "levelId": "expert",
    "levelName": "Expert",
    "title": "Leitura Rápida e Encorpada de Texto Técnico-Filosófico",
    "instructions": "Ler um texto complexo em ritmo acelerado, mas mantendo rigorosamente o registro grave e a precisão articulatória impecável.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "Frases/Textos;OOOOOOOOOOOOOOOOOOO",
    "partB": "A complexidade da fonação humana reflete a própria estrutura do pensamento. Quando a mecânica respiratória, a ressonância torácica e a agilidade da máscara se fundem em um único vetor, a comunicação deixa de ser um ato mecânico e passa a ser uma força da natureza, moldada pela inteligência e executada com perfeição."
  },
  {
    "id": 60,
    "dayId": "sexta",
    "dayName": "Sexta-feira",
    "dayFocus": "Frente de Integração de Fluxo e Articulação Avançada",
    "levelId": "expert",
    "levelName": "Expert",
    "title": "Improvisação de Alta Performance com Transições Dinâmicas",
    "instructions": "Improvisar um discurso de 1 minuto aplicando mudanças repentinas de ritmo e volume, sem nunca perder a ancoragem no grave e a pureza do fluxo.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "Frases/Textos;UUUUUUUUUUUU, OOOOOOOOOOO",
    "partB": "A verdadeira liberdade vocal é aquela que não conhece limites de tessitura nem barreiras de tensão. Seja sussurrando um segredo nas sombras ou proclamando um decreto no topo da montanha, a voz integrada permanece sempre fiel à sua raiz, inesgotável em sua potência e impecável em sua clareza."
  },
  {
    "id": 61,
    "dayId": "sabado",
    "dayName": "Sábado",
    "dayFocus": "Frente de Sequência Completa de Vogais e Fricção",
    "levelId": "iniciante",
    "levelName": "Iniciante",
    "title": "Fricção Contínua com 'J' (JJJJ)",
    "instructions": "Emitir o som fricativo JJJJ com a garganta relaxada e boca em posição de semiconcha por 6 segundos. 5 repetições.",
    "durationSeconds": 6,
    "repetitions": 5,
    "partA": "Frases/Textos;JJJJJJJJJJJJJJJJJJJJ.....",
    "partB": "Jjjj... garganta solta... fluxo controlado."
  },
  {
    "id": 62,
    "dayId": "sabado",
    "dayName": "Sábado",
    "dayFocus": "Frente de Sequência Completa de Vogais e Fricção",
    "levelId": "iniciante",
    "levelName": "Iniciante",
    "title": "Escala Simples de Vogais (A-E-I-O-U)",
    "instructions": "Emitir a sequência A-E-I-O-U em tom confortável, focando na clareza de cada vogal. 5 repetições.",
    "durationSeconds": null,
    "repetitions": 5,
    "partA": "Frases/Textos",
    "partB": "A, É, Ê, I, Ó, Ô, U\n, É, Ê, I, Ó, Ô, U\n, É, Ê, I, Ó, Ô, U\n, É, Ê, I, Ó, Ô, U\n, É, Ê, I, Ó, Ô, U\nA PIPA CAIU\nO ELEFANTE É GRANDE\nLUA ALUMIA A RUA\nO AVIÃO VOA ALTO."
  },
  {
    "id": 63,
    "dayId": "sabado",
    "dayName": "Sábado",
    "dayFocus": "Frente de Sequência Completa de Vogais e Fricção",
    "levelId": "iniciante",
    "levelName": "Iniciante",
    "title": "Combinação J + Vogal",
    "instructions": "Emitir Jjjj por 3 segundos e abrir imediatamente para a vogal O grave. 4 repetições.",
    "durationSeconds": 3,
    "repetitions": 4,
    "partA": "Frases/Textos\nJJJJJJJJJJJJ- OOOOOOOOOOO\nJJJJJJJJJJJJJ- OOOOOOOOOOO\nJJJJJJJJJJJJJ- OOOOOOOOOOO\nJJJJJJJJJJJJ- OOOOOOOOOOOO",
    "partB": "VVVVVVVVVVV- UUUUUUUU\nVVVVVVVVVVV- UUUUUUUUUU\nVVVVVVVVVVV- UUUUUUUUUU\nVVVVVVVVVVV- UUUUUUUUUU\nVVVVVVVVVVV- UUUUUUUUUU"
  },
  {
    "id": 64,
    "dayId": "sabado",
    "dayName": "Sábado",
    "dayFocus": "Frente de Sequência Completa de Vogais e Fricção",
    "levelId": "medio",
    "levelName": "Médio",
    "title": "Fricção Prolongada com Curva de Tom (JJJJ)",
    "instructions": "Emitir JJJJ por 8 segundos fazendo uma curva descendente do médio para o grave. 4 repetições.",
    "durationSeconds": 8,
    "repetitions": 4,
    "partA": "Frases/Textos\nJJJJJJJJJJJJJJJJJJJJJ..\nJJJJJJJJJJJJJJJJJJJJJJ...\nJJJJJJJJJJJJJJJJJJJJJJ...\nJJJJJJJJJJJJJJJJJJJJJJ.",
    "partB": "O som fricativo limpa o trato vocal, preparando o espaço para as vogais profundas."
  },
  {
    "id": 65,
    "dayId": "sabado",
    "dayName": "Sábado",
    "dayFocus": "Frente de Sequência Completa de Vogais e Fricção",
    "levelId": "medio",
    "levelName": "Médio",
    "title": "Sequência de Vogais com Abertura Oral Controlada",
    "instructions": "Emitir a sequência A-E-I-O-U descendo o tom progressivamente em cada vogal. 3 séries.",
    "durationSeconds": null,
    "repetitions": 3,
    "partA": "Frases/Textos ; AAAAAAAAAAA\nEEEEEEEEEEE\nIIIIIIIIIIIIIIIIIIII\nOOOOOOOOO\nUUUUUUUUU.",
    "partB": "As vogais moldam o espaço interno da boca, permitindo que a luz e o som se expandam sem barreiras."
  },
  {
    "id": 66,
    "dayId": "sabado",
    "dayName": "Sábado",
    "dayFocus": "Frente de Sequência Completa de Vogais e Fricção",
    "levelId": "medio",
    "levelName": "Médio",
    "title": "Leitura de Frases com Foco em Modulação Vocálica",
    "instructions": "Ler frases destacando a transição suave entre vogais abertas e fechadas.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "Frases/Textos; ´\nÉÉÉÉÉÉÉ......ÊÊÊÊÊÊÊ^\nÉÉÉÉÉÉÉ......ÊÊÊÊÊÊÊ\nÉÉÉÉÉÉÉ......ÊÊÊÊÊÊÊ\nÉÉÉÉÉÉÉ......ÊÊÊÊÊÊÊ",
    "partB": "O eco da noite atravessa o espaço, unindo todas as vogais em um único fluxo harmônico."
  },
  {
    "id": 67,
    "dayId": "sabado",
    "dayName": "Sábado",
    "dayFocus": "Frente de Sequência Completa de Vogais e Fricção",
    "levelId": "profissional",
    "levelName": "Profissional",
    "title": "Fricção Intensa seguida de Emissão Plena de Vogais (JJJJ + A-E-I-O-U)",
    "instructions": "Executar 10 segundos de JJJJ com máxima abertura faríngea e, em seguida, emitir a escala de vogais em tom grave e ressonante. 3 repetições.",
    "durationSeconds": 10,
    "repetitions": 3,
    "partA": "Frases/Textos\nJJJJJJJJJJJJJ- A- E- I- O- U\nJJJJJJJJJJJJJ- A- E- I- O- U\nJJJJJJJJJJJJJ- A- E- I- O- U.",
    "partB": "O arco das vogais — do aberto 'A' ao fechado 'U' — forma a paleta de cores da nossa expressão. Dominar a passagem por esse espectro com fonação limpa é esculpir a matéria sonora com precisão escultural."
  },
  {
    "id": 68,
    "dayId": "sabado",
    "dayName": "Sábado",
    "dayFocus": "Frente de Sequência Completa de Vogais e Fricção",
    "levelId": "profissional",
    "levelName": "Profissional",
    "title": "Leitura Poética com Foco na Geometria das Vogais",
    "instructions": "Ler um poema lírico concentrando-se na mudança geométrica da boca para cada vogal, mantendo a laringe baixa.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "Frases/Textos\nA, É, Ê, I, Ó, Ô, U\n, É, Ê, I, Ó, Ô, U\n, É, Ê, I, Ó, Ô, U\n, É, Ê, I, Ó, Ô, U\n, É, Ê, I, Ó, Ô, U",
    "partB": "Nas margens do rio sagrado, as vogais desenham o contorno do silêncio. Cada som é uma arquitetura de ar e espaço, onde a laringe repousa em paz e a ressonância preenche o templo do corpo."
  },
  {
    "id": 69,
    "dayId": "sabado",
    "dayName": "Sábado",
    "dayFocus": "Frente de Sequência Completa de Vogais e Fricção",
    "levelId": "profissional",
    "levelName": "Profissional",
    "title": "Sequência de Vogais com Variação Dinâmica (Piano a Forte)",
    "instructions": "Emitir a sequência A-E-I-O-U no registro grave, iniciando sussurrado e crescendo até o limite da projeção sem perder o timbre escuro.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "A, É, Ê, I, Ó, Ô, U\n, É, Ê, I, Ó, Ô, U\n, É, Ê, I, Ó, Ô, U\n, É, Ê, I, Ó, Ô, U\n, É, Ê, I, Ó, Ô, U",
    "partB": "Da suavidade do sopro à potência do trovão, a voz molda as vogais com soberania e controle inabalável."
  },
  {
    "id": 70,
    "dayId": "sabado",
    "dayName": "Sábado",
    "dayFocus": "Frente de Sequência Completa de Vogais e Fricção",
    "levelId": "expert",
    "levelName": "Expert",
    "title": "Monólogo de Arquitetura Acústica e Pureza Vocélica",
    "instructions": "Fazer a fricção JJJJ de alta abertura e declamar um texto filosófico exigindo pureza absoluta em cada vogal e ressonância plena.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "JJJJJJJJJJJJJJJJJ...",
    "partB": "A palavra perfeita nasce da geometria exata do trato vocal. Quando as vogais A, E, I, O, U são emitidas com integridade acústica impecável e sustentadas por uma fricção controlada, a voz transcende a mera comunicação e atinge o patamar da arte pura, onde cada formante é uma obra-prima de ressonância e profundidade."
  },
  {
    "id": 71,
    "dayId": "sabado",
    "dayName": "Sábado",
    "dayFocus": "Frente de Sequência Completa de Vogais e Fricção",
    "levelId": "expert",
    "levelName": "Expert",
    "title": "Leitura Interpretativa de Texto Clássico com Tessitura Plena",
    "instructions": "Ler um trecho clássico explorando todas as nuances de abertura das vogais, mantendo o centro de gravidade no registro grave e ressonante.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "JJJJJJJJJJJJJJJJJ, A- E- I- O- U\nJJJJJJJJJJJJJJJJJ, A- E- I- O- U\nJJJJJJJJJJJJJJJJJ, A- E- I- O- U\nJJJJJJJJJJJJJJJJJ, A- E- I- O- U.",
    "partB": "No vasto teatro da existência, a voz é o instrumento que dá forma ao invisível. A modulação precisa das vogais, unida à solidez inegociável do grave, confere ao discurso o poder de erguer impérios ou pacificar tempestades, revelando a maestria suprema da arte da palavra falada."
  },
  {
    "id": 72,
    "dayId": "sabado",
    "dayName": "Sábado",
    "dayFocus": "Frente de Sequência Completa de Vogais e Fricção",
    "levelId": "expert",
    "levelName": "Expert",
    "title": "Improvisação Melódica com Domínio Absoluto do Trato Vocal",
    "instructions": "Improvisar um discurso solene utilizando passagens contínuas entre fricção e vogais abertas/fechadas, demonstrando controle total da ressonância.",
    "durationSeconds": null,
    "repetitions": null,
    "partA": "A, É, Ê, I, Ó, Ô, U\n, É, Ê, I, Ó, Ô, U\n, É, Ê, I, Ó, Ô, U\n, É, Ê, I, Ó, Ô, U\n, É, Ê, I, Ó, Ô, U.",
    "partB": "O domínio do trato vocal é a conquista definitiva da autoexpressão. Quando o espaço interno, a laringe relaxada e a pureza das vogais convergem em perfeita harmonia, o som gerado torna-se a extensão perfeita da alma, soberano, eterno e imune ao tempo."
  }
] as VocalExercise[];

export const weekDays = [
  { id: 'segunda', label: 'Segunda', short: 'SEG', focus: 'Fluxo & estabilidade' },
  { id: 'terca', label: 'Terça', short: 'TER', focus: 'Máscara & língua' },
  { id: 'quarta', label: 'Quarta', short: 'QUA', focus: 'Peito & graves' },
  { id: 'quinta', label: 'Quinta', short: 'QUI', focus: 'Projeção frontal' },
  { id: 'sexta', label: 'Sexta', short: 'SEX', focus: 'Integração vocal' },
  { id: 'sabado', label: 'Sábado', short: 'SÁB', focus: 'Vogais & fricção' },
] as const;

export const levels = [
  { id: 'iniciante', label: 'Iniciante', description: 'Base e consciência' },
  { id: 'medio', label: 'Médio', description: 'Coordenação e apoio' },
  { id: 'profissional', label: 'Profissional', description: 'Densidade e resistência' },
  { id: 'expert', label: 'Expert', description: 'Controle avançado' },
] as const;

export function getExercise(id: number) {
  return weeklyRoutine.find((exercise) => exercise.id === id) ?? weeklyRoutine[0];
}
